"""
Heartbeat Watchdog - L3: Processing Layer

Detects silent failures via heartbeat timeout.
Tracks heartbeat timestamps and emits timeout events via callback.

Part of the 5-layer architecture defined in ARCHITECTURE.md.

Author: Vmin Judge Tool Development
Version: 1.0
"""

from __future__ import annotations

import time
import logging
from dataclasses import dataclass
from typing import List, Callable, Optional, Dict, Any
from threading import Lock, Event

# Configure module logger
logger = logging.getLogger(__name__)


@dataclass
class HeartbeatEvent:
    """Event generated by heartbeat tracking."""
    event_type: str  # 'heartbeat', 'timeout', 'start', 'stop'
    timestamp: float
    heartbeat_count: int = 0
    elapsed_since_last: float = 0.0
    data: Dict[str, Any] = None

    def __post_init__(self):
        if self.data is None:
            self.data = {}


class HeartbeatWatchdog:
    """
    Detects silent failures via heartbeat timeout.

    A "silent failure" occurs when the workload process hangs or crashes
    without outputting an explicit error message. The only way to detect
    this is by monitoring for periodic heartbeat messages.

    If no heartbeat is received for longer than `timeout_sec`, a timeout
    event is triggered, indicating SILENT_FAILURE.

    Attributes:
        timeout_sec: Maximum time between heartbeats before timeout (default 45s).
        last_heartbeat: Timestamp of last heartbeat received.
        heartbeat_count: Total number of heartbeats received.

    Usage:
        watchdog = HeartbeatWatchdog(timeout_sec=45)
        watchdog.register_callback(my_timeout_handler)

        # In main loop:
        if 'HEARTBEAT' in line:
            watchdog.reset(time.time())

        if watchdog.check_timeout():
            print("Silent failure detected!")
    """

    DEFAULT_TIMEOUT_SEC = 45

    def __init__(self, timeout_sec: int = None):
        """
        Initialize HeartbeatWatchdog.

        Args:
            timeout_sec: Timeout in seconds. Defaults to 45.
        """
        self.timeout_sec = timeout_sec if timeout_sec is not None else self.DEFAULT_TIMEOUT_SEC
        self.last_heartbeat: Optional[float] = None
        self.heartbeat_count = 0
        self.start_time: Optional[float] = None
        self.end_time: Optional[float] = None
        self._is_running = False

        self._callbacks: List[Callable] = []
        self._timeout_callbacks: List[Callable] = []
        self._event_callbacks: List[Callable] = []

        self._lock = Lock()
        self._last_check: Optional[float] = None
        self._last_timeout_elapsed: float = 0.0
        self._timeout_triggered = False

        # History for debugging
        self._event_history: List[HeartbeatEvent] = []
        self._max_history = 100

    @property
    def is_running(self) -> bool:
        """Check if watchdog is running (started)."""
        return self._is_running

    @property
    def elapsed_since_last_heartbeat(self) -> float:
        """Get time elapsed since last heartbeat."""
        with self._lock:
            if self.last_heartbeat is None:
                return 0.0 if self.start_time is None else time.time() - self.start_time
            return time.time() - self.last_heartbeat

    def start(self):
        """Start the watchdog timer."""
        with self._lock:
            if not self._is_running:
                self.start_time = time.time()
                self.last_heartbeat = None
                self.heartbeat_count = 0
                self._is_running = True
                self._timeout_triggered = False
                self._emit_event(HeartbeatEvent(
                    event_type='start',
                    timestamp=self.start_time,
                    heartbeat_count=0,
                    elapsed_since_last=0.0
                ))
                logger.debug("HeartbeatWatchdog started")

    def stop(self):
        """Stop the watchdog timer."""
        with self._lock:
            if self._is_running:
                self.end_time = time.time()
                self._is_running = False
                self._emit_event(HeartbeatEvent(
                    event_type='stop',
                    timestamp=self.end_time,
                    heartbeat_count=self.heartbeat_count,
                    elapsed_since_last=time.time() - self.last_heartbeat if self.last_heartbeat else 0.0
                ))
                logger.debug(f"HeartbeatWatchdog stopped (count={self.heartbeat_count})")

    def reset(self, timestamp: float = None):
        """
        Reset watchdog timer on heartbeat received.

        Args:
            timestamp: Unix timestamp of heartbeat. Defaults to current time.
        """
        if timestamp is None:
            timestamp = time.time()

        with self._lock:
            self.last_heartbeat = timestamp
            self.heartbeat_count += 1

            # Record heartbeat event
            self._emit_event(HeartbeatEvent(
                event_type='heartbeat',
                timestamp=timestamp,
                heartbeat_count=self.heartbeat_count,
                elapsed_since_last=0.0
            ))

            logger.debug(f"Heartbeat #{self.heartbeat_count} at {timestamp}")

    def check_timeout(self) -> bool:
        """
        Check if heartbeat timeout has been exceeded.

        Calls registered timeout callbacks if timeout detected.

        Returns:
            True if timeout exceeded and not already triggered.
        """
        with self._lock:
            if not self._is_running:
                return False

            if self.last_heartbeat is None:
                # No heartbeat yet - check against start time
                if self.start_time is None:
                    return False
                elapsed = time.time() - self.start_time
            else:
                elapsed = time.time() - self.last_heartbeat

            self._last_check = time.time()
            self._last_timeout_elapsed = elapsed

            # Only trigger timeout once
            if elapsed > self.timeout_sec and not self._timeout_triggered:
                self._timeout_triggered = True
                self._on_timeout(elapsed)
                return True

            return False

    def _on_timeout(self, elapsed: float):
        """Handle timeout event."""
        logger.warning(f"Heartbeat timeout: {elapsed:.1f}s > {self.timeout_sec}s")

        # Record timeout event
        self._emit_event(HeartbeatEvent(
            event_type='timeout',
            timestamp=time.time(),
            heartbeat_count=self.heartbeat_count,
            elapsed_since_last=elapsed,
            data={'timeout_sec': self.timeout_sec}
        ))

        # Call timeout callbacks
        for callback in self._timeout_callbacks:
            try:
                callback(elapsed)
            except Exception as e:
                logger.error(f"Error in timeout callback: {e}")

    def _emit_event(self, event: HeartbeatEvent):
        """Emit event to registered callbacks."""
        self._event_history.append(event)
        if len(self._event_history) > self._max_history:
            self._event_history.pop(0)

        for callback in self._event_callbacks:
            try:
                callback(event)
            except Exception as e:
                logger.error(f"Error in event callback: {e}")

    def register_callback(self, callback: Callable):
        """
        Register general callback for timeout events.

        Deprecated: Use register_timeout_callback() instead.

        Args:
            callback: Function to call with elapsed time on timeout.
        """
        self.register_timeout_callback(callback)

    def register_timeout_callback(self, callback: Callable[[float], None]):
        """
        Register callback for timeout events.

        Callback receives the elapsed time in seconds since last heartbeat.

        Args:
            callback: Function to call on timeout.
        """
        if callback not in self._timeout_callbacks:
            self._timeout_callbacks.append(callback)

    def register_event_callback(self, callback: Callable[[HeartbeatEvent], None]):
        """
        Register callback for all heartbeat events.

        Args:
            callback: Function to call for each event.
        """
        if callback not in self._event_callbacks:
            self._event_callbacks.append(callback)

    def unregister_callback(self, callback: Callable):
        """Unregister a callback."""
        if callback in self._timeout_callbacks:
            self._timeout_callbacks.remove(callback)
        if callback in self._event_callbacks:
            self._event_callbacks.remove(callback)

    def get_status(self) -> Dict[str, Any]:
        """
        Get current watchdog status.

        Returns:
            Dictionary with status information.
        """
        with self._lock:
            elapsed = 0.0
            if self.last_heartbeat is not None:
                elapsed = time.time() - self.last_heartbeat
            elif self.start_time is not None:
                elapsed = time.time() - self.start_time

            return {
                'is_running': self._is_running,
                'timeout_sec': self.timeout_sec,
                'heartbeat_count': self.heartbeat_count,
                'last_heartbeat': self.last_heartbeat,
                'elapsed_since_last': elapsed,
                'timeout_triggered': self._timeout_triggered,
                'last_check': self._last_check,
                'last_timeout_elapsed': self._last_timeout_elapsed,
                'start_time': self.start_time,
                'duration': (self.end_time or time.time()) - self.start_time if self.start_time else 0.0
            }

    def get_event_history(self) -> List[HeartbeatEvent]:
        """Get recent heartbeat events."""
        with self._lock:
            return list(self._event_history)

    def get_heartbeats_per_minute(self) -> float:
        """
        Calculate average heartbeats per minute.

        Returns:
            Heartbeats per minute, or 0.0 if not enough data.
        """
        with self._lock:
            if not self._is_running or self.start_time is None:
                return 0.0

            if self.heartbeat_count < 2:
                return 0.0

            duration = (self.end_time or time.time()) - self.start_time
            if duration <= 0:
                return 0.0

            return (self.heartbeat_count / duration) * 60.0

    def was_timeout(self) -> bool:
        """Check if a timeout was ever triggered."""
        with self._lock:
            return self._timeout_triggered

    def set_timeout(self, timeout_sec: int):
        """
        Update the timeout value.

        Args:
            timeout_sec: New timeout in seconds.
        """
        self.timeout_sec = timeout_sec

    def reset_state(self):
        """Reset all state without stopping."""
        with self._lock:
            self.last_heartbeat = None
            self.heartbeat_count = 0
            self._timeout_triggered = False
            self._event_history.clear()

    def __repr__(self) -> str:
        status = self.get_status()
        return (f"HeartbeatWatchdog(timeout={status['timeout_sec']}s, "
                f"count={status['heartbeat_count']}, "
                f"elapsed={status['elapsed_since_last']:.1f}s, "
                f"running={status['is_running']})")


class HeartbeatPatternDetector:
    """
    Detects heartbeat patterns in log lines.

    This class provides utilities for detecting heartbeat patterns
    in log output and automatically feeding them to a watchdog.

    Usage:
        detector = HeartbeatPatternDetector()
        detector.register_watchdog(watchdog)

        for line in lines:
            if detector.is_heartbeat(line):
                detector.on_heartbeat(line, timestamp)
    """

    # Common heartbeat patterns
    HEARTBEAT_PATTERNS = [
        b'HEARTBEAT',
        b'heartbeat',
        b'KEEPALIVE',
        b'keep_alive',
        b'ping',
        b'PING',
    ]

    def __init__(self):
        """Initialize detector."""
        self._watchdogs: List[HeartbeatWatchdog] = []
        self._pattern_strings = [p.decode() if isinstance(p, bytes) else p for p in self.HEARTBEAT_PATTERNS]

    def register_watchdog(self, watchdog: HeartbeatWatchdog):
        """Register a watchdog to feed."""
        if watchdog not in self._watchdogs:
            self._watchdogs.append(watchdog)

    def is_heartbeat(self, line) -> bool:
        """
        Check if line contains a heartbeat pattern.

        Args:
            line: String or ParsedLine to check.

        Returns:
            True if line appears to be a heartbeat.
        """
        content = line.content if hasattr(line, 'content') else str(line)
        content_lower = content.lower()

        for pattern in self._pattern_strings:
            if pattern.lower() in content_lower:
                return True
        return False

    def on_heartbeat(self, line, timestamp: float = None):
        """
        Handle detected heartbeat.

        Resets all registered watchdogs.

        Args:
            line: The heartbeat line (for metadata extraction if needed).
            timestamp: Unix timestamp.
        """
        for watchdog in self._watchdogs:
            watchdog.reset(timestamp)

    def extract_iteration(self, line) -> Optional[int]:
        """
        Extract iteration number from heartbeat line.

        Args:
            line: String or ParsedLine containing heartbeat.

        Returns:
            Iteration number if found, None otherwise.
        """
        content = line.content if hasattr(line, 'content') else str(line)

        import re
        # Match patterns like "iteration=123" or "iteration: 123"
        match = re.search(r'iteration[=:]\s*(\d+)', content, re.IGNORECASE)
        if match:
            return int(match.group(1))
        return None

    def __repr__(self) -> str:
        return f"HeartbeatPatternDetector(patterns={len(self._pattern_strings)}, "
